import numpy as np
import pandas as pd
from numpy.random import RandomState
from typing import Self, Dict, Mapping, TypeVar, Generic
import numpy.typing as npt
from sklearn.tree import BaseDecisionTree
from sklearn.utils.validation import check_is_fitted

T = TypeVar("T")

class LeafNodeSampler:
    """
    Adds a leaf-based synthetic sampling functionality to any fitted
    decision tree estimator. The sampler generates synthetic target values based on 
    the empirical target distributions observed in the leaf nodes of a 
    fitted decision tree.

    The class implements a tree-based sampling strategy:
    - During the fitting phase, each leaf node stores a histogram of 
    observed target values.
    - During the transform phase, synthetic targets are generated by
    sampling from the histogram of the leaf that a new observation falls into.

    The stored data structure s:
        leaf_map: Dict[int, Dict[T, int]]
    where:
        leaf_id -> {target_value -> count}

    Usage:
    class TreeMethod(BaseDecisionTree):
        def __init(tree_sampler: LeafNodeSampler | None = None):
            self.tree_sampler = tree_sampler
            
        def fit(self, X, y):
            super().fit(X, y)
            if self.tree_sampler is None:
                self.tree_sampler_= LeafNodeSampler()
            else:
                self.tree_sampler_ = clone(self.tree_sampler)
            self.tree_sampler_.fit_sampler(self, X, y)
            return self
        
        def transform(self, X_syn):
            return self.tree_sampler_.sample_from_leaves(X_syn)
    """
    def __init__(self, random_state: int | None = None):
        self.random_state = random_state
        pass

    def fit_sampler(self, tree: BaseDecisionTree, X: npt.ArrayLike, y: npt.ArrayLike) -> Self:
        """
        Build the leaf node histogram mapping from observed data.

        The method assigns each sample in `X` to a leaf node of the fitted
        decision tree and records the frequency of each target value `y` observed
        in that leaf.

        The resulting mapping is stored in `self._leaf_map` and has the form:
            leaf_id -> {target_value -> count}

        :param X: Feature matrix used to determine leaf membership
        :param y: Target values corresponding to the rows of `X`
        :return: Fitted sampler
        
        Example:
        --------
        
        """
        check_is_fitted(tree)
        self.tree_ = tree
        
        pass

    def sample_from_leaves(self, X_syn: npt.ArrayLike) -> np.ndarray:
        """
        Generate synthetic target values for new samples.

        For each sample in `X_syn`, the method determines the leaf
        node reached in the decision tree and retrieves the corresponding
        histogram of observed target values stored during fitting.

        A value is then sampled from the histogram using the counts
        as sampling weights.

        :param X_syn: Feature matrix of synthetic samples for which target values
            should be generated.
        :param random_state: Seed used to reproduce randomness
        :return: Sampled synthetic target values
        """
        pass