import numpy as np
import pandas as pd
from typing import Self, Dict, Mapping, TypeVar, Generic
import numpy.typing as npt
from sklearn.tree import BaseDecisionTree
from sklearn.base import BaseEstimator
from sklearn.utils.validation import check_is_fitted
from sklearn.utils import check_random_state

T = TypeVar("T")

class LeafNodeSampler(BaseEstimator):
    """
    Adds a leaf-based synthetic sampling functionality to any fitted
    decision tree estimator. The sampler generates synthetic target values based on 
    the empirical target distributions observed in the leaf nodes of a 
    fitted decision tree.

    The class implements a tree-based sampling strategy:
    - During the fitting phase, each leaf node stores a histogram of 
    observed target values.
    - During the transform phase, synthetic targets are generated by
    sampling from the histogram of the leaf that a new observation falls into.

    The stored data structure s:
        leaf_map: Dict[int, Dict[T, int]]
    where:
        leaf_id -> {target_value -> count}

    Usage:
    class TreeMethod(BaseDecisionTree):
        def __init(tree_sampler: LeafNodeSampler | None = None):
            self.tree_sampler = tree_sampler
            
        def fit(self, X, y):
            super().fit(X, y)
            if self.tree_sampler is None:
                self.tree_sampler_= LeafNodeSampler()
            else:
                self.tree_sampler_ = clone(self.tree_sampler)
            self.tree_sampler_.fit_sampler(self, X, y)
            return self
        
        def transform(self, X_syn):
            return self.tree_sampler_.sample_from_leaves(X_syn)
    """
    def __init__(self, random_state: int | None = None):
        self.random_state = random_state
        pass

    def fit_sampler(self, tree: BaseDecisionTree, X: npt.ArrayLike, y: npt.ArrayLike) -> Self:
        """
        Build the leaf node histogram mapping from observed data.

        The method assigns each sample in `X` to a leaf node of the fitted
        decision tree and records the frequency of each target value `y` observed
        in that leaf.

        The resulting mapping is stored in `self._leaf_map` and has the form:
            leaf_id -> {target_value -> count}

        :param X: Feature matrix used to determine leaf membership
        :param y: Target values corresponding to the rows of `X`
        :return: Fitted sampler
        
        Example:
        --------
        
        """
        check_is_fitted(tree)
        
        X = np.asarray(X)
        y = np.asarray(y)

        if X.shape[0] != y.shape[0]:
            raise ValueError(
                f"X and y must have the same number of samples. "
                f"Got {X.shape[0]} and {y.shape[0]}"
            )

        leaf_ids = tree.apply(X)
        self._leaf_map = {}

        for leaf_id, target in zip(leaf_ids, y):
            if leaf_id not in self._leaf_map:
                self._leaf_map[leaf_id] = {}

            leaf_hist = self._leaf_map[leaf_id]

            if pd.isna(target):
                key = np.nan
                leaf_hist[key] = leaf_hist.get(key, 0) + 1
            else:
                leaf_hist[target] = leaf_hist.get(target, 0) + 1

        self.tree_ = tree

        if self.random_state is None:
            self.random_state_ = check_random_state(seed=42)
        else:
            self.random_state_ = check_random_state(self.random_state)

        return self

    def sample_from_leaves(self, X_syn: npt.ArrayLike) -> np.ndarray:
        """
        Generate synthetic target values for new samples.

        For each sample in `X_syn`, the method determines the leaf
        node reached in the decision tree and retrieves the corresponding
        histogram of observed target values stored during fitting.

        A value is then sampled from the histogram using the counts
        as sampling weights.

        :param X_syn: Feature matrix of synthetic samples for which target values
            should be generated.
        :param random_state: Seed used to reproduce randomness
        :return: Sampled synthetic target values
        """
        
        check_is_fitted(self, ["tree_", "_leaf_map", "random_state_"])
        X_syn = np.asarray(X_syn)

        leaf_ids = self.tree_.apply(X_syn)
        n_samples = len(leaf_ids)

        y_syn = np.empty(n_samples, dtype=object)

        for i, leaf_id in enumerate(leaf_ids):
            if leaf_id not in self._leaf_map:
                raise ValueError(
                    f"Leaf id {leaf_id} not seen during fitting."
                )
            
            leaf_hist = self._leaf_map[leaf_id]
            values = np.array(list(leaf_hist.keys()), dtype=object)
            counts = np.array(list(leaf_hist.values()), dtype=np.int32)

            if counts.sum() == 0:
                y_syn[i] = np.nan
                continue

            probs = counts / counts.sum()
            y_syn[i] = self.random_state_.choice(values, p=probs)

        return y_syn