import numpy as np
import pandas as pd
from numpy.random import RandomState
from typing import Self, Dict, Mapping, TypeVar, Generic
import numpy.typing as npt
from sklearn.tree import BaseDecisionTree

T = TypeVar("T")

class LeafNodeSampler(Generic[T]):
    """
    Sampler that generates synthetic target values based on the empirical
    target distributions observed in the leaf nodes of a fitted decision tree.

    The class implements a tree-based sampling strategy:
    - During the fitting phase, each leaf node stores a histogram of 
    observed target values.
    - During the transform phase, synthetic targets are generated by
    sampling from the histogram of the leaf that a new observation falls into.

    The stored data structure s:
        leaf_map: Dict[int, Dict[T, int]]
    where:
        leaf_id -> {target_value -> count}
    """
    def __init__(self, 
                 tree: BaseDecisionTree,
                 random_state: RandomState | None | int = None) -> None:
        self.tree: BaseDecisionTree = tree
        self.leaf_map: Dict[int, Dict[T, int]] = {}
        self.random_state = random_state

    def fit(self, X: npt.ArrayLike, y: npt.ArrayLike) -> Self:
        """
        Build the leaf node histogram mapping from observed data.

        The method assigns each sample in `X` to a leaf node of the fitted
        decision tree and records the frequency of each target value `y` observed
        in that leaf.

        The resulting mapping has the form:
            leaf_id -> {target_value -> count}

        :param X: Feature matrix used to determine leaf membership
        :param y: Target values corresponding to the rows of `X`
        :return: Fitted sampler
        
        Example:
        --------
        
        """
        pass

    def sample(self, X_syn: npt.ArrayLike) -> npt.ArrayLike:
        """
        Generate synthetic target values for new samples.

        For each sample in `X_syn`, the method determines the leaf
        node reached in the decision tree and retrieves the corresponding
        histogram of observed target values stored during fitting.

        A value is then sampled from the histogram using the counts
        as sampling weights.

        :param X_syn: Feature matrix of synthetic samples for which target values
            should be generated.
        :return: Sampled synthetic target values
        """
        pass